### PR TITLE
#163388251 Add Social authentication via google and facebook

### PR DESCRIPTION
**Pull request by calebrotich**
#### What does this PR do?
Adds backend implementation of social login with google and facebook

#### How should this be manually tested?
_1. Ensure you have the below exports in your environment. The sample data provided can be used._
`export FACEBOOK_KEY=<facebook_key_value>`
`export FACEBOOK_SECRET=<facebook_secret>`
`export GOOGLE_OAUTH2_KEY=<google_auth_key_value>`
`export GOOGLE_OAUTH2_SECRET=<google_auth_secret>`
`export OAUTH2_ACCESS_TOKEN= <facebook_long_term_auth_token>`
_2. Run server_
_3. At postman, make a `post` request to ```http://127.0.0.1:8000/api/social/login/```_ with the body having the sample data below:
 **facebook**
`{
    "provider":"facebook",
     "access_token":"<OAUTH2_ACCESS_TOKEN_GOOGLE>"
}`
**google**
`{
    "provider":"google-oauth2",
     "access_token":"<OAUTH2_ACCESS_TOKEN_GOOGLE>"
}`
#### Any background context you want to provide?
Use `https://developers.google.com/oauthplayground` to generate your own google access token
#### What are the relevant pivotal tracker stories?
[#163388251](https://www.pivotaltracker.com/story/show/163388251)
#### Screenshots (if appropriate)
**Google**
image
**Facebook**
image

### CODE REVIEW

**Review by bryan-munene — APPROVED** [review]
LGTM

**Review by bryan-munene — COMMENTED** [review]
@calebrotich10 I would suggest the URL be similar to the others. `users/social/`

**Comment by TooColline** [comment]
Hey, @calebrotich10 this looks good to me. I like how you've implemented this.

**Comment by calebrotich** [comment]
> @calebrotich10 I would suggest the URL be similar to the others. `users/social/`

Sounds great. The link, however, will be used to initiate the social auth process and will never be visible in the browser.

**Review by sam-karis — APPROVED** [review]
Good work

**Comment by calebrotich** [comment]
> Good work

Thank you. @sam-karis

**Pull request merged**
