### PR TITLE
#163388253 feature create user profile

### PR DESCRIPTION
**Pull request by unah254**
#### What does this PR do?
Have profile for a user upon registration
#### Description of Task to be completed?
- write unit tests
- create models, views, serializers and renderers for profile
- register profiles URL
#### How should this be manually tested?
* clone the repo and `cd` into it.
* checkout to the branch
  `git checkout ft-users-create-profile-163388253`

* `pip install -r requirements.txt`

* Run server
  `python manage.py runserver`

* test on postman using
-  the url `http://127.0.0.1:8000/api/users/` to register an author

- Using the token provided upon registration, add it on authorization header and use the url `http://127.0.0.1:8000/api/profiles/<str: username>` to view an author

- the url `http://127.0.0.1:8000/api/profiles` to view all authors

- the url ` http://127.0.0.1:8000/api/profiles/edit/<str:username>` to edit a profile. Add token on the authorization header and input the following on the form data. 

N.B You cannot edit another author's profile. 

image

* Updated profile should appear

#### Any background context you want to provide?
This must be an authorized user, therefore, a token is added on the authorization header
image

#### What are the relevant pivotal tracker stories?
[#163388253](https://www.pivotaltracker.com/n/projects/2240063)
#### Screenshots (if appropriate)
 View all authors 
image
View a specific author
image
Edit your profile
image

### CODE REVIEW

**Comment by bryan-munene** [comment]
Deploy and test on Heroku, to ensure that it works when merged to develop

**Comment by TooColline** [comment]
Hi, @unah254 Please be more descriptive in your PR description with how to manually test the feature. Especially after running the server, say something like after registering a user, test on postman by placing the username on the URL and provide a screenshot for that and another one when a user tries to edit a profile which is not theirs. Otherwise, great work.

**Comment by unah254** [comment]
@TooColline @bryan-munene noted with thanks, it's updated now

**Review by sam-karis — APPROVED** [review]
LGTM

**Pull request merged**
